# Generated by Django 5.0 on 2023-12-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pic', models.ImageField(upload_to='productpics')),
                ('prize', models.IntegerField()),
            ],
        ),
    ]
