# Generated by Django 5.0 on 2023-12-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('dawn', 'dawn'), ('addidas', 'addidas'), ('nike', 'nike')], default='dawn', max_length=10),
        ),
    ]
